Karnage/histogram
cpp-gamedev/noiz pull request #2
Opened 2023-09-24 02:14 UTC by GDBobby

generates 1d perlin noise and converts it to a bmp image of a histogram. 
size of image is controllable via command line, from 256 to 4096, in multiples of 256

2023-09-24 04:46 UTC, karnkaul commented
Uh, I don't see any changes 😅

2023-09-24 05:38 UTC, GDBobby commented
ok hopefully its good now

2023-09-24 16:24 UTC, karnkaul requested changes
Nice work! Some changes needed before it's good to be merged.

I noticed that this file uses `camelCase` where none of the others in the project do. It's not a big deal, but it may confuse readers a bit.

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/CMakeLists.txt
Generally the convention for user-facing binaries is either `kebab-case` or `PascalCase`, `noiz-HistogramBitmap` is a mix of both.

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/CMakeLists.txt
> +  HistogramBitmap.cpp
I prefer to stick to `snake_case` for file paths because different OSs have different path case sensitivities.

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
Looks good overall! Needs some small changes:
- Run `clang-format` (Format Document) on the file, this can be done automatically on save if you like (in VSCode).
- Fix the linter warnings (install the `clang-tidy` plugin if you don't see any warnings).

Screenshot as example of linter issues (all the stuff highlighted green, as well as the hover window on a specific one):

![image](https://github.com/cpp-gamedev/noiz/assets/16272243/246a8f49-7481-463c-b7fb-c6bf70c2728d)

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +	struct BmpHeader {
Alternatively, you could use PPM as the output format instead, much easier to deal with.

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +};
Technically this is repeated code, but since it's supposed to be a self-contained example it's fine. Perhaps if we add more examples, we could add a common header with this stuff that's shared among all of them. Thoughts?

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +		assert(imageSize > 0 && imageSize <= 16);
Don't `assert` about an input that could be anything, it will unnecessarily crash the program. Instead print the error and return false. Similarly, the "unrecognized argument" part is handled here, so it doesn't need to be printed again in main.

```suggestion
		if (imageSize < 0 || imageSize > 16) {
		    std::cerr << std::format("invalid image size: '{}'\n", imageSize);
		    return false;
		}
```

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +	struct Color{
`Rgb` might be a better name, since `Color` is a bit ambiguous. (Could be RGB / RGBA / CMYK / hex code / etc.)

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +		void writeToFile(std::ofstream& outFile){
Member function should be `const`.

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +		}
Use member list initialization instead of assignment in the constructor body.

```suggestion
		BmpInfoHeader(uint16_t const imageSize) : width(imageSize), height(imageSize)
```

2023-09-24 16:24 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +	void writeImage() {
Member function should be `const`.

2023-09-24 17:55 UTC, GDBobby commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +};
For sure. Is there a metaprogramming style to iterate through every member of an unknown object? Never been able to figure it out before.

2023-09-24 19:47 UTC, karnkaul commented on examples/HistogramBitmap/HistogramBitmap.cpp
> +};
Not yet, that will require reflection (C++26 earliest).

2023-09-24 20:49 UTC, GDBobby commented
Tempted to not allow the construction of the BMP header struct outside of the static writing function.
Hopefully fine now.

2023-09-25 18:39 UTC, closed without merging

2023-09-25 18:39 UTC, GDBobby commented
usage covered by example is caught in a cross section between the plaintext histogram, and the texture generator found in another example.
Closing branch